name: "Pull Request Labeler"
on:
  - pull_request

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v1-preview
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"