apiVersion: v1
kind: Service
metadata:
  name: kafka-monitor
  labels:
    service: kafka-monitor
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: kafka-monitor
  type: LoadBalancer
