name: CI

on:
  pull_request:
    types: ['opened', 'synchronize']

jobs:
  ci:
    strategy:
      matrix:
        dists: 
        - version: '11.0.13+8.1'
          dist: 'microsoft'

    name: ci
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.dists.version }}
        distribution: ${{ matrix.dists.dist }}
    - name: test
      run: ./gradlew --info test --no-daemon